export const ON_LOADING_ADMIN_TOOLS_INIT = 'ON_LOADING_ADMIN_TOOLS_INIT';
export const ON_ASSIGNING_ROLE_TO_COURSE = 'ON_ASSIGNING_ROLE_TO_COURSE';
export const ON_ASSIGNING_GLOBAL_ROLE = 'ON_ASSIGNING_GLOBAL_ROLE';
export const ON_CLEAR_SELECTED_CONTACT = 'ON_CLEAR_SELECTED_CONTACT';
