export const ON_LOADING_ADMIN_TOOLS_INIT = 'ON_LOADING_ADMIN_TOOLS_INIT';
export const ON_ASSIGNING_ROLE_TO_COURSE = 'ON_ASSIGNING_ROLE_TO_COURSE';
export const ON_ASSIGNING_GLOBAL_ROLE = 'ON_ASSIGNING_GLOBAL_ROLE';
export const ON_CLEAR_SELECTED_CONTACT = 'ON_CLEAR_SELECTED_CONTACT';
export const ON_UPSERTING_COURSE = 'ON_UPSERTING_COURSE';
export const ON_LOADING_CONTACT_COURSE_PROGRESS_ACTIVITY = 'ON_LOADING_CONTACT_COURSE_PROGRESS_ACTIVITY';
export const ON_LOADING_CONTACT_LOGIN_FOOTPRINT = 'ON_LOADING_CONTACT_LOGIN_FOOTPRINT';
export const ON_LOADING_ALL_USER_LOGIN_FOOTPRINT = 'ON_LOADING_ALL_USER_LOGIN_FOOTPRINT';
