export const DEFAULT = 'DEFAULT';
export const ON_RENDERING_ADMIN_INSIGHTS_DASHBOARD = 'ON_RENDERING_ADMIN_INSIGHTS_DASHBOARD';
export const ON_RENDERING_LOCATION_TYPE_SELECTIONS = 'ON_RENDERING_LOCATION_TYPE_SELECTIONS';
export const ON_GETTING_COUNTRIES_BY_LOCATION_TYPE = 'ON_GETTING_COUNTRIES_BY_LOCATION_TYPE';
export const ON_LOADING_ALL_DASHBOARD_CONTENTS = 'ON_LOADING_ALL_DASHBOARD_CONTENTS';
