export const DEFAULT = 'DEFAULT';
export const ON_RENDERING_ADMIN_INSIGHTS_DASHBOARD = 'ON_RENDERING_ADMIN_INSIGHTS_DASHBOARD';
export const ON_RENDERING_LOCATION_TYPE_SELECTIONS = 'ON_RENDERING_LOCATION_TYPE_SELECTIONS';
export const ON_GETTING_COUNTRIES_BY_LOCATION_TYPE = 'ON_GETTING_COUNTRIES_BY_LOCATION_TYPE';
export const ON_LOADING_ALL_DASHBOARD_CONTENTS = 'ON_LOADING_ALL_DASHBOARD_CONTENTS';
export const ON_LOADING_USER_AUTHENTICATED_PROGRESS_DASHBOARD = 'ON_LOADING_USER_AUTHENTICATED_PROGRESS_DASHBOARD';
export const ON_SUBMITTING_ADMIN_ENROLLEE_PROGRESS = 'ON_SUBMITTING_ADMIN_ENROLLEE_PROGRESS';
export const ON_LOADING_FACILITADOR_DASHBOARD_CONTENTS = 'ON_LOADING_FACILITADOR_DASHBOARD_CONTENTS';
