export const ON_PURCHASING_PRODUCT = 'ON_PURCHASING_PRODUCT';
export const ON_GETTING_PRODUCTS_FOR_PURCHASE = 'ON_GETTING_PRODUCTS_FOR_PURCHASE';
export const ON_GETTING_PRODUCTS_PURCHASED_BY_USER = 'ON_GETTING_PRODUCTS_PURCHASED_BY_USER';