name: publish to gc buckets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  DEV_DOMAIN_NAME: dev.titulino.com
  PROD_DOMAIN_NAME: titulino.com
  CACHE_BUCKET_NAME: github-actions-cache-162166941288
  GIT_TOKEN: ${{ secrets.TITULINO_GITHUB_TOKEN }}
  ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  ENV_INPUT: ${{ inputs.env }}
  CI: false
  NODE_OPTIONS: "--max_old_space_size=4096"
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_BUCKET_NAME: ${{ github.ref == 'refs/heads/main' && 'titulino.com' || 'dev.titulino.com' }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      # Authenticate with Google Cloud
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Install Google Cloud SDK
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Cache npm modules
      - name: Cache npm modules
        id: npm-cache
        run: |
          if gsutil -q stat gs://${CACHE_BUCKET_NAME}/cip/npm_cache.tgz; then
            echo "Cache found. Restoring from GCS..."
            gsutil cp gs://${CACHE_BUCKET_NAME}/cip/npm_cache.tgz npm_cache.tgz
            tar -xzf npm_cache.tgz
          fi

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Gulp globally
      - name: Install Gulp CLI
        run: npm install -g gulp-cli

      # Run Gulp tasks to process CSS
      - name: Run Gulp Tasks
        run: |
          gulp less
          gulp theme
          gulp less

      # Build React app
      - name: Build React App
        run: |
          if [ "$ENV" = "dev" ]; then
            echo "Building for development..."
            NODE_ENV=development npm run build
          else
            echo "Building for production..."
            NODE_ENV=production npm run build
          fi

      # Upload to GCS with Cache Busting
      - name: Upload to GCS
        run: |
          echo "npm version --> $(npm -v)"
          echo "node version --> $(node -v)"

          # Output current environment variable for debugging
          echo "process.env.ENVIRONMENT --> $ENVIRONMENT"

          [ -n "${ENV_INPUT}" ] && export ENV=${ENV_INPUT}
          echo "ENV--> ${ENV} ENV_INPUT--> ${ENV_INPUT}"
          export ENVIRONMENT=${ENV}

          # Print the environment after the change
          echo "After setting ENV, process.env.ENVIRONMENT --> $ENVIRONMENT"

          # Replace the placeholder with actual ENV value
          sed -i "s/process.env.ENVIRONMENT/\"${ENV}\";/" src/configs/EnvironmentConfig.js

          # Check if the bucket is empty before removing files
          if gsutil -q stat gs://${GCP_BUCKET_NAME}/*; then
            echo "Bucket is not empty. Removing old files..."
            gsutil -m rm -r gs://${GCP_BUCKET_NAME}/*
          else
            echo "Bucket is empty. Skipping file removal."
          fi

          # Sync new build to the bucket
          # Upload files normally
          gsutil -m rsync -r build gs://${GCP_BUCKET_NAME}

          # Set cache control headers for critical files
          gsutil -m setmeta -h "Cache-Control: no-store, no-cache, must-revalidate, max-age=0" gs://${GCP_BUCKET_NAME}/index.html
          gsutil -m setmeta -h "Cache-Control: no-store, no-cache, must-revalidate, max-age=0" gs://${GCP_BUCKET_NAME}/service-worker.js

          # Add a content hash to service worker (optional, but better)
          #SW_HASH=$(sha256sum build/service-worker.js | awk '{ print $1 }')
          #gsutil cp build/service-worker.js gs://${GCP_BUCKET_NAME}/service-worker-${SW_HASH}.js

          # Ensure the app loads the correct service worker dynamically
          #sed -i "s|service-worker.js|service-worker-${SW_HASH}.js|g" build/index.html
          #gsutil cp build/index.html gs://${GCP_BUCKET_NAME}/index.html
